### ISSUE TITLE
FetchHttpResource 并不完全等同ngResource,并且在合并URL函数上存在BUG

### ISSUE THREAD

**Issue by cjd6568358** [kuitos/es6-utils#1]
urlTemplate传入http://www.baidu.com会被genUrlFromTemplate函数转换成http:/www.baidu.com

**Comment by cjd6568358** [comment]
另外你这个项目还维护吗？shuyun==数云？

**Comment by cjd6568358** [comment]
sorry,Npm上拉的是web-http-fetch 那个版本是不是不维护了？

**Comment by kuitos** [comment]
不知道你说的 web-http-fetch 这个库是啥库。。

**Comment by cjd6568358** [comment]
https://cnpmjs.org/package/web-fetch-request 还有action 不支持url参数啊 ngResource是支持的

我改了下源代码：
var url = genUrlFromTemplate(urlTemplate + (configs.url || ''), extractParams);
还有你是在数云吗？

**Comment by cjd6568358** [comment]
fetch的then函数没写也会报错。。。

**Comment by kuitos** [comment]
不太记得发过这个库。。 npm 上也找不到。。 你用 es6-http-utils 这个就好了

**Comment by cjd6568358** [comment]
我提的这些BUG能帮忙改掉吗

**Comment by kuitos** [comment]
es6-http-utils 里也有这个 bug ？

**Comment by cjd6568358** [comment]
有的啊  
var url = genUrlFromTemplate(urlTemplate + (configs.url || ''), extractParams);
return response.data.then(function (data) { 
这一行没有判断then函数是否存在，IE9下面return response.data.then&&response.data.then(function (data) { 
还是有问题

**Comment by cjd6568358** [comment]
太多问题了，返回的response也是残缺不全

**Comment by kuitos** [comment]
github 上提 issue 最好给出具体代码示例(markdown 语法可以看 [这里](https://guides.github.com/features/mastering-markdown/#syntax) )，描述出具体问题😀

这个库目前可能不会花时间维护了，建议用这个库代替 [axios](https://github.com/mzabriskie/axios)
